config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :questions

  resource :session, only: %i[new create destroy]
  resources :users, except: %i[index]
  resources :hashtags, param: :name, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  HASHTAG_REGEXP = /#[[:word:]-]+/

  before_validation :downcase_name

  validates :name, presence: true, uniqueness: true

  has_many :question_hashtags, dependent: :destroy
  has_many :questions, through: :question_hashtags

  def to_param
    name
  end

  def downcase_name
    name&.downcase!
  end
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true, length: { maximum: 400 }

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_many :question_hashtags, dependent: :destroy
  has_many :hashtags, through: :question_hashtags

  after_save_commit :save_hashtags

  private
  
  def save_hashtags
    hashtag_names = find_hashtags("#{body} #{answer}")

    self.hashtags = 
      hashtag_names.map do |hashtag_name|
        Hashtag.find_or_create_by(name: hashtag_name)   
      end
  end

  def find_hashtags(text)
    text.scan(Hashtag::HASHTAG_REGEXP)
        .map { |hashtag| hashtag.delete('#').downcase }
        .uniq
  end
end

app/models/question_hashtag.rb
class QuestionHashtag < ApplicationRecord
  belongs_to :question
  belongs_to :hashtag
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :nickname, use: :slugged

  has_secure_password

  before_validation :downcase_nickname, :downcase_email

  validates :email, presence: true, uniqueness: true, format: { with:  URI::MailTo::EMAIL_REGEXP }
  validates :nickname, uniqueness: true, length: 3..40, format: { with: /\A[a-zA-Z0-9_]+\z/ }

  has_many :questions, dependent: :delete_all

  include Gravtastic
  gravtastic(secure: true, filetype: :png, size: 100, default: 'retro')
  
  private

  def downcase_nickname
    nickname&.downcase!
  end

  def downcase_email
    email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'Вам туда нельзя!'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find_by!(name: params[:name])
    @questions = @hashtag.questions.order(created_at: :desc)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy edit]
  before_action :set_question_for_current_user, only: %i[update destroy edit]  
  
  def create
    question_params = params.require(:question).permit(:body, :user_id)
    
    @question = Question.new(question_params)
    @question.author = current_user

    if @question.save
      redirect_to user_path(@question.user), notice: 'Новый вопрос создан'
    else
      flash.now[:alert] = 'Не получилось создать вопрос'

      render :new
    end
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)

    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Сохранили вопрос!'
    else
      flash.now[:alert] = 'Не получилось редактировать вопрос'

      render :edit
    end
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user), notice: 'Вопрос удалён!'
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.order(created_at: :desc).first(10)
    @users = User.order(created_at: :desc).first(10)
    @hashtags = Hashtag.joins(:questions).distinct
  end

  def new
    @user = User.find(params[:user_id])
    @question = Question.new(user: @user)
  end

  def edit
  end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Вы вошли на сайт'
    else
      flash.now[:alert] = 'Неправильный email или пароль' 
      
      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy show]
  before_action :authorize_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      
      redirect_to root_path, notice: 'Вы успешно зарегистрировались!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля регистрации'

      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)   
      redirect_to root_path, notice: 'Данные пользователя обновлены!'
    else
      flash.now[:alert] = 'При попытке сохранить пользователя возникли ошибки'

      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удалён'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @question = Question.new(user: @user)
  end

  private

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation, :color
    )
  end

  def authorize_user
    redirect_with_alert unless current_user == @user
  end

  def set_user
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def display_hashtag(hashtag)
    "##{hashtag.name}"
  end

  def render_with_links(text)
    found_hashtags = text.scan(Hashtag::HASHTAG_REGEXP)

    found_hashtags.each do |found_hashtag|
      hashtag = Hashtag.find_by(name: found_hashtag.delete('#').downcase)

      text.gsub!(found_hashtag, link_to(found_hashtag, hashtag_path(hashtag)))
    end

    text
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def display_nickname(user)
    "@#{user.nickname}"
  end
end

app/views/hashtags/show.html.erb
<div class='container mt-sm container-br'>
  <h2 class='title-lg'>
    <%= display_hashtag(@hashtag) %>
  </h2>
</div>

<% @questions.each do |question| %>
  <div class='mt-sm container container-br'>
    <div class='text-sm mb-sm text-grey'>
      <span>вопрос <%= link_to "##{question.id}", question_path(question) %></span>
      <%= render partial: 'questions/author', locals: { question: question } %>
      <span>для <%= link_to display_nickname(question.user), user_path(question.user) %></span>
    </div>
    <%= render question %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='wrapper'>
      <% if current_user.present? %>
        <div class='navbar' style='background-color: <%= current_user.color %>'>
      <% else %>
        <div class='navbar navbar-default'>
      <% end %>
        <p class='title-sm text-bold'><%= link_to 'Ask me!', root_path %></p>
        <div>
          <% if current_user.present? %>
            <%= link_to display_nickname(current_user), user_path(current_user), class: 'mr-sm' %>
            <%= button_to 'Выйти', session_path, method: :delete, class: 'button button-navbar' %>
          <% else %>
            <%= link_to 'Регистрация', new_user_path, class: 'button button-navbar mr-sm' %>
            <%= link_to 'Вход', new_session_path, class: 'button button-navbar' %>
          <% end %>
        </div>
      </div>

      <% if flash[:notice].present? %>
        <p class='mb mt message message-notice'><%= flash[:notice] %>
      <% elsif flash[:alert].present? %>
        <p class='mb mt message message-alert'><%= flash[:alert] %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_author.html.erb
<% if question.author.present? %>
  <span>от <%= link_to display_nickname(question.author), user_path(question.author) %></span>
<% else %>
  <span>от анонима</span>
<% end %>

app/views/questions/_form.html.erb
<% if question.errors.any? %>
  <div class='mt'>
    <% question.errors.full_messages.each do |message| %>
      <p class='mb-sm text-red'><%= message %></p>
    <% end %>
  </div>
<% end %>

<%= form_with model: question, data: {turbo: false} do |form| %>
  <%= form.hidden_field :user_id %>

  <p><%= form.label :body, 'Текст вопроса' %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

  <% if question.persisted? %>
    <p class='mt'><%= form.label :answer, 'Ваш ответ' %></p>
    <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
  <% end %>
  
  <p class='mt'>
    <%= form.submit 'Сохранить', class: 'button button-main' %>
  </p>
<% end %>

app/views/questions/_question.html.erb
<div class='mb-sm'>
  <%= simple_format h(question.body) %>
</div>

<% if question.answer.present? %>
  <div class='mb-sm text-answer'>
    <%= simple_format h(question.answer) %>
  </div>
<% end %>

<div class='text-sm question-footer'>
  <div class='text-grey'>
    <%= l(question.created_at, format: :short) %>
    
    <% question.hashtags.each do |hashtag| %>
      <%= link_to display_hashtag(hashtag), hashtag_path(hashtag) %>
    <% end %>
  </div>

  <% if current_user == question.user %>
    <div>
      <% edit_icon = question.answer.present? ? 'pencil' : 'reply' %>
      <%= link_to fa_icon(edit_icon), edit_question_path(question), title: 'Ответить на вопрос', class: 'mr-sm' %>
      <%= button_to fa_icon('trash-o'), question_path(question), form: {data: {turbo_confirm: 'Точно удалить вопрос?'}},
        method: :delete, title: 'Удалить вопрос' %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class='container container-br-b'>
  <h2 class='title-lg mb-sm'>Редактирование вопроса #<%= @question.id %></h2>
  <div class='mb'>
    <%= render 'author', question: @question %>
  </div>

  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class='container container-br-b'>
  <h2 class='title-lg mb'>Недавно добавились</h2>
  <div class='users-box'>
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: {user: user} %>
    <% end %>
  </div>
</div>

<% if @hashtags.any? %>
  <div class='container mt-sm container-br'>
    <% @hashtags.each do |hashtag| %>
      <%= link_to display_hashtag(hashtag), hashtag_path(hashtag) %>
    <% end %>
  </div>
<% end %>

<div class='container mt-sm container-br'>
  <h2 class='title-lg'>
    <%= inclination(@questions.count, 'Последний', 'Последние', 'Последние') %>
    <%= @questions.count %>
    <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
  </h2>
</div>

<% @questions.each do |question| %>
  <div class='mt-sm container container-br'>
    <div class='text-sm mb-sm text-grey'>
      <span>вопрос <%= link_to "##{question.id}", question_path(question) %></span>
      <%= render 'author', question: question %>
      <span>для <%= link_to display_nickname(question.user), user_path(question.user) %></span>
    </div>
    <%= render 'question', question: question %>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class='container container-br-b'>
  <h2 class='title-lg mb-sm'>Новый вопрос</h2>
  <p class='mb'>для <%= link_to display_nickname(@question.user), user_path(@question.user)%>
  
  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class='container container-br-b'>
  <h2 class='title-lg mb-sm'>Вопрос #<%= @question.id %></h2>
  
  <div class='mb'>
    <%= render 'author', question: @question %>
    <span>для <%= link_to display_nickname(@question.user), user_path(@question.user) %></span>
  </div>

  <%= render 'question', question: @question %>
</div>

app/views/users/_errors.html.erb
<div class='mt'>
  <% errors.full_messages.each do |message| %>
    <p class='mb-sm text-red'><%= message %></p>
  <% end %>
</div>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg-#{user.id % 5}" %>

<div class='users-box-user <%= background_class %> rounded mt' >
  <a href='<%= user_path(user) %>'>
    <%= image_tag user.gravatar_url, title: display_nickname(user), class: 'rounded' %>
  </a>
</div>

app/views/users/edit.html.erb
<div class='container container-br-b'>
  <h2 class='title'>Редактировать профиль</h2>

  <div class='mt'>
    <p><%= image_tag @user.gravatar_url, title: display_nickname(@user), class: 'rounded' %>
    <p class='text-sm mt mb'>Чтобы добавить или поменять аватар - зарегистрируйтесь на
      <%= link_to 'Gravatar', 'https://gravatar.com' %> и загрузите фото</p>
  </div>

  <%= render 'errors', errors: @user.errors if @user.errors.any? %>

  <%= form_with model: @user, data: {turbo: false} do |form| %>
    <p><%= form.label :name, 'Имя' %></p>
    <p><%= form.text_field :name, class: 'form-text-field' %></p>

    <p class='mt'><%= form.label :nickname, 'Никнейм на сайте' %></p>
    <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

    <p class='mt'><%= form.label :color, 'Цвет шапки' %></p>
    <p><%= form.color_field :color %></p>

    <p class='mt-lg text-sm'> Если не хотите менять пароль - оставьте эти поля пустыми</p>
    
    <p class='mt'><%= form.label :password %></p>
    <p><%= form.password_field :password, class: 'form-text-field' %></p>

    <p class='mt'><%= form.label :password_confirmation %></p>
    <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

    <p class='mt-lg'>
      <%= form.submit 'Сохранить', class: 'button button-main' %>
      <span class='text-sm'>или <%= link_to 'вернуться', :back %></span>
    </p>
  <% end %>

  <div class='mt-lg'>
    <%= button_to 'Удалить профиль', user_path(@user),
      method: :delete,
      form: {data: {turbo_confirm: 'Вы точно хотите удалить свой профиль?'}},
      class: 'text-red text-sm'
    %>
  </div>
</div>

app/views/users/new.html.erb
<div class='container container-br-b'>
  <h2 class='title'>Регистрация</h2>

  <%= render 'errors', errors: @user.errors if @user.errors.any? %>

  <div class='mt'>
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, 'Имя' %></p>
      <p><%= form.text_field :name, class: 'form-text-field' %></p>

      <p class='mt'><%= form.label :nickname, 'Никнейм на сайте' %></p>
      <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

      <p class='mt'><%= form.label :email %></p>
      <p><%= form.text_field :email, class: 'form-text-field' %></p>

      <p class='mt'><%= form.label :password %></p>
      <p><%= form.password_field :password, class: 'form-text-field' %></p>

      <p class='mt'><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

      <p class='mt-lg'><%= form.submit 'Зарегистрироваться', class: 'button button-main' %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class='user-box'>
  <h2 class='title-lg mt-lg'><%= @user.name %></h2>
  <div class='mt'>
    <%= render partial: 'users/user_avatar', locals: {user: @user} %>
  </div>
  <% if current_user == @user %>
    <p class='mt mb-lg'>
      <%= link_to fa_icon('pencil'), edit_user_path(@user), title: 'Редактировать профиль' %>
    </p>
  <% end %>
  <p class='text-bold mt mb-lg'><%= display_nickname(@user) %></p>
</div>

<div class='container container-br-b'>
  <%# <%= link_to 'Спроси меня', new_question_path(user_id: @user.id), class: 'button button-main' %>
  <p>
    <%= render 'questions/form', question: @question %>
  <p>
</div>

<div class='container mt-sm container-br'>
  <% if @questions.any? %>
    <h2 class='title-lg'>
      <%= @questions.count %>
      <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
    </h2>
  <% else %>
    <p>У этого пользователя пока никто ничего не спросил. Задай ему вопрос!</p>
  <% end %>
</div>

<% if @questions.any? %>
  <% @questions.each do |question| %>
    <div class='mt-sm container container-br'>
      <div class='text-sm mb-sm text-grey'>
        <span>вопрос <%= link_to "##{question.id}", question_path(question) %></span>
        <%= render 'questions/author', question: question %>
      </div>
      <%= render question %>
    </div>
  <% end %>
<% else %>
  <%= image_tag 'no-messages.png', class: 'no-message-image mt-lg' %>
<% end%>